basket1={"apple","bannana","mango","grape","watermelon"}
basket2={"guava,cocunut,bannana,pineapple,"}
print("basket1",basket2)
print("basket2",basket2)
basket1.add("orange")
print("basket1 after adding orange",basket1)
commom_fruits=basket1.intersection(basket2)
print("fruits in baskets:",commom_fruits)
import array as arr
fruit_counts=arr.array("i",[3,2,5,4])
print("fruit counts array",fruit_counts)
fruit_counts.insert(0,1)
fruit_counts.append(6)
print("fruit adding items", fruit_counts)
count_of_4=fruit_counts.append(4)
print("number of times 4 appears:",count_of_4)
fruit_counts.reverse()
print("reversed fruit array",fruit_counts.reverse)
print("")
print("class fruit organizer ")
print("basket1",basket2)
print("basket2",basket1)
print("shared fruits:",commom_fruits)
print("fruit_counts:",fruit_counts)
print("")